name: FuzzyChat
main: be.darnell.mc.FuzzyChat.FuzzyChat
softdepend: [ FuzzyLog, bPermissions, Privileges ]
version: 1.0.1
author: cedeel
description: Chat formatting plugin for Bukkit
permissions:
  fuzzychat.chat.color:
    description: Colorize messages
  fuzzychat.chat.magic:
    description: Randomize messages
  fuzzychat.chat.stylize:
    description: Stylize messages
  fuzzychat.admin:
    description: Manage prefixes and suffixes
    default: op
  fuzzychat.setprefix:
    description: Assign prefixes
    default: op
  fuzzychat.setsuffix:
    description: Assign suffixes
    default: op
  fuzzychat.setnick:
    description: Assign nicknames
    default: op
  fuzzychat.whois:
    description: Lookup usernames
    defualt: op
commands:
  hc:
    description: Management command
    permission: fuzzychat.admin
  setprefix:
    description: Assign prefixes
    permission: fuzzychat.setprefix
  setsuffix:
    description: Assign suffixes
    permission: fuzzychat.setsuffix
  setnick:
    description: Assign nicknames
    permission: fuzzychat.setnick
  whois:
    description: Lookup usernames
    permission: fuzzychat.whois
